### ISSUE TITLE
Persist languages of cells when re-opening a notebook

### ISSUE THREAD

**Issue by DonJayamanne** [dotnet/interactive#1038]
Assume a user creates notebook today with 3 cells:
* First cell is C#
* Second cell is Powershell
* Third cell is C#
User runs against .NET interactive kernel in VS Code, saves this & opens it again.

The Jupyter Extension will not know about the languages.
At best, the 3 cells will be `C#` (again this is based on the metadata stored in the notebook document.
I believe @brettfo is making changes to update the metadata.

One way to address is for .NET Interactive to add metadata into each of the cells:
* As users create cells or update the languages of the cells, the .NET Interactive can update the metadata stored in each cell.
* The Jupyter extension will store this metadata in IPYNB
* Next time Jupyter opens this ipynb, we'll look for this metadta & the cells will now have their langauges

Thoughts? @brettfo /cc

**Comment by brettfo** [comment]
We have in `main` (but not published yet) almost exactly that; when a language is set we add metadata like `"dotnet_interactive": { "language": "csharp" }` and when our kernel is active we map that metadata to our specific flavor of C# `dotnet-interactive.csharp` so that our language services get invoked properly.  According to the [.ipynb spec](https://nbformat.readthedocs.io/en/latest/format_description.html#cell-metadata) there isn't a well-known language field, hence we namespaced our own.

We do have an outstanding issue, however; in the old world where we were responsible for .ipynb reading and writing, we would prepend something like `#!pwsh` on save and when reading if we saw the first line was `#!pwsh` we'd strip this out and set the language appropriately.  We've gotten some pushback on this via #1024.  The other issue, though, is that if we don't own writing back to .ipynb, we can set the cell metadata but we can't prepend `#!pwsh` so if that same notebook is then opened in Jupyter lab, the user has no way of knowing or changing the cell's language (execution, however, is fine because that cell metadata is sent back to us and we can sniff it out.)

**Comment by DonJayamanne** [comment]
Looks like we might have to agree on a convention here, as other Jupyter kernels can have multiple languages and we'd need to support storing the language informaiton in the metata ourselves.
I.e. we can store the language information in the cell metadata & it will work for .NET notebooks as well as ruby notebooks & other Jupyter notebooks (e.g. sos).
E.g. something like `vscode: {language:<xyz>}`, still undecided.

**Comment by brettfo** [comment]
I'm certainly up for renaming the `dotnet_interactive` namespace to something else, but I don't think `vscode` is it because we also need to work in Jupyter Lab and while we could do it, I don't think it makes much sense for our Jupyter Lab kernel to peek into `vscode` metadata to try to find the cell's language.

This also gets more complicated in that from Jupyter's perspective (and the user) the language is `csharp`, but according to VS Code the language is `dotnet-interactive.csharp` because we have some additional syntax that we support and we need our own language services to be called, not the ones registered by OmniSharp.

Because of both of those, I think it would be best for our extension to handle our own metadata (I'm up for suggestions on renaming it), unless we have some mechanism to tell your extension that when it sees a language of `csharp` that really means `dotnet-interactive.csharp` (similarly for our own special variants of F#, PowerShell, HTML, JavaScript, and SQL).
