### ISSUE TITLE
Failing to use with VSCode native notebook feature and .NET 5

### ISSUE THREAD

**Issue by Morgam** [dotnet/interactive#1188]
The getting started instructions of .NET Interactive Notebooks guides to do the following:
-Install the latest Visual Studio Code.
-Install the latest .NET 5 SDK
-Install the .NET Interactive Notebooks extension from the marketplace.

Even though it seems to be simple, it is something I can’t get working. For example, if I try to run simple line of C# code “Console.WriteLine("something");” after installing as instructed above, I’ll get “NameError: name 'Console' is not defined” (with “C# (.NET Interactive)” selected for the cell).

Please help. This is very cool development in the .NET ecosystem and I would like to present its possibilities to the organizations I work with.

An idea: could there be a sample folder with Dockerfile and devcontainer.json files, with which one can easily reproduce the environment enabling the latest and greatest features.

**Comment by jonsequitur** [comment]
This will happen if the Python kernel rather than .NET Interactive is being used. 

![image](https://user-images.githubusercontent.com/547415/112495898-89d8a780-8d41-11eb-9483-65192601002f.png)

When you see this, you can change kernels by selecting **View: Reopen Editor With...** from the command pallet and then choose **.NET Interactive for Jupyter**:

![image](https://user-images.githubusercontent.com/547415/112496018-a543b280-8d41-11eb-9c7a-2904380f69af.png)
![image](https://user-images.githubusercontent.com/547415/112497836-336c6880-8d43-11eb-9eb5-a5fa2d063816.png)
![image](https://user-images.githubusercontent.com/547415/112498237-90681e80-8d43-11eb-9dc6-2993b83f04b1.png)

**Comment by Morgam** [comment]
Super, thank you so much @jonsequitur. That was the reason.

In my view, the Getting Started instructions (at  
https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode ) should have a note about this. I almost gave up on this feature.
