### ISSUE TITLE
Support for Powershell desktop as a user configuration or additional Kernel choice

### ISSUE THREAD

**Issue by BW-PA** [dotnet/interactive#1225]
When attempting to install and import the powershell module BcContainerHelper I get the following error during import stage

`Install-Module BcContainerHelper -force`
`Import-Module BCContainerHelper`

`Import-Module: 
Line |
   2 |  Import-Module BCContainerHelper 
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The script 'BcContainerHelper.psm1' cannot be run because it contained a "#requires" statement for PowerShell editions 'Desktop'. The edition of PowerShell that is required by the script does not match the currently running PowerShell Core edition.`

I believe the issue is because .net interactive uses the cross platform powershell core edition and the module I'm attempting to use requires the desktop edition of powershell.

The same commands work successfully in Azure Data Studio which is using the Powershell Desktop Kernel

Adding support for Powershell Desktop edition either as a user configuration or as an additional Kernel choice would solve the problem.

**Comment by daxian-dbw** [comment]
Starting from PowerShell 7.1, in order to provide better backward compatibility, the `Import-Module` cmdlet was improved to allow importing a module to a Windows PowerShell session (by starting powershell.exe as a background process, and using the `implicit remoting` feature in PowerShell core to talk with it):

![save](https://user-images.githubusercontent.com/127450/117528449-2b7d2680-af87-11eb-9b52-bc2052a5350a.jpg)

For a Windows PowerShell module that doesn’t work natively in PowerShell Core, this is how we are supposed to work around it.

I tried to run `Import-Module -UseWindowsPowerShell` in .NET interactive PS sub-kernel on Windows, and it failed with the following error.
This is because PowerShell remoting has a legacy dependency on `BinaryFormatter`, which is obsoleted in .NET 5. The obsoletion was suppressed in PowerShell itself, but since it’s not in .NET interactive, it fails with this `NotSupportedException`.

![save1](https://user-images.githubusercontent.com/127450/117528480-5c5d5b80-af87-11eb-94a0-16da865397d1.jpg)

Back to your question, you cannot launch powershell.exe (Windows desktop PowerShell) from within the PS sub-kernel in .NET interactive, as there is no RPEL to interact with it.
As for “how feasible to support Windows PowerShell”, it may not be too much work from the coding perspective, as the PS sub-kernel code may just work and you may only need to build it against .NET 4.7.1 with the [PowerShell 5.1 reference assemblies](https://www.nuget.org/packages/Microsoft.PowerShell.5.1.ReferenceAssemblies/) instead. But I’m not sure how it would be integrated in .NET interactive.

**Comment by BW-PA** [comment]
I'd forgotten about the -UseWindowsPowershell parameter.  Though as you point out it doesn't help in this situation.  My original question is not to support Powershell Desktop _within_ PowerShell Core but instead, to allow targeting the PowerShell desktop Kernel explicitly.  Either as an available Kernel from the list of Kernels within a .net interactive notebook code block or as an extension setting for .net interactive that controlled which PowerShell Kernel was being targeted.

**Comment by BW-PA** [comment]
And by extension, being able to install other kernels into a .net Interactive notebook would be useful via the same mechanism.  Powershell Desktop just happens to be the one I want.  But you only have to look at the list of available Jupyter Kernels to see the potential that a NuGet kernel install for .net Interactive would have.

**Comment by jonsequitur** [comment]
Installing new .NET Interactive subkernels via NuGet is supported today. You can see a very simple with our support for [Mermaid](https://github.com/dotnet/interactive/blob/main/src/Microsoft.DotNet.Interactive.ExtensionLab/MermaidKernelExtension.cs) and a more complex example with our support for [T-SQL](https://github.com/dotnet/interactive/tree/main/src/Microsoft.DotNet.Interactive.SqlServer).

**Comment by brettfo** [comment]
Closing in favor of #2183.
