### ISSUE TITLE
Neat way to load the latest prerelease package via #r

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/interactive#1277]
A normal way to load the latest package from NuGet is
```
#r "nuget:DuckPackage"
```

But if only we want to install the latest including prereleases, it would be ugly and non-obvious

```
#r "nuget:DuckPackage, *-*"
```

What if we could add a parameter

```
#r "nuget:DuckPackage" --include-prerelease
```

It looks a bit more wordy, but it's not ugly, and it's consistent with VS' NuGet manager. What do you think?

**Comment by jonsequitur** [comment]
`#r` and `#i` existed in C# and F# before .NET Interactive or we might well have done something more like the magic commands. This syntax was discussed, as it would be more consistent and have better support for completions and help like the other magic commands do:

```console
#!nuget DuckPackage --version 1.2.3
#!nuget DuckPackage.Interactive --prerelease
```

Aligning with the `dotnet` CLI was also discussed because it would allow people to use what they know from one context in the other.

**Comment by WhiteBlackGoose** [comment]
So is `#!nuget` going to be implemented at some point in time?

**Comment by KevinRansom** [comment]
@WhiteBlackGoose, maybe ... but I wouldn't count on it.  Generally we try to avoid doing the same thing several different ways.

**Comment by brettfo** [comment]
The version syntax `*-*` is how NuGet references prerelease packages and is governed by the `nuget:` prefix, not at the `#r` level.
