### ISSUE TITLE
Opening namespace/module after referencing nuget package doesn't work on a kernel extension

### ISSUE THREAD

**Issue by PawelStadnicki** [dotnet/interactive#1307]
I have F# kernel extension in which (among other requirements) I want to reference nuget packages (to avoid doing  it in the editor and disturbing users from proper value)  AND open namespaces.

My OnLoadAsync method contains following code piece :

```
let code = 
    [
        "#r nuget:Feliz"
        "open Feliz"
    ] |> String.concat Environment.NewLine
    
    kernel.VisitSubkernelsAndSelf(
        function
        | :? FSharpKernel as fs  -> 

            fs.SendAsync(SubmitCode (code,"fsharp")) 
                        |> Async.AwaitTask 
                        |> Async.RunSynchronously
        | _ -> ()
    )
```

Package loads successfully but it fails upon opening namespaces/modules:

`Error: input.fsx (2,6)-(2,11) typecheck error The namespace or module 'Feliz' is not defined. `

Exactly the same code inserted into cell works fine:

```
r# nuget:Feliz
open Feliz
```
Is this kernel extension limitation/ by design ? I suspect rather that it is more kernel context operation involved that I may use in a wrong way

**Comment by jonsequitur** [comment]
This code is intended to work. I debugged it and it looks like the submission parser is splitting this into two commands `"#r nuget:Feliz"` and `"open Feliz"` (which is expected) but then the second is incorrectly getting routed to the C# kernel. You should be able to work around this by sending each of these separately to the F# kernel.

(Unrelated, the `.Wait()` call makes me a little nervous. I don't think you should see a deadlock because we're not using a `SynchronizationContext` but I tend to avoid this as a matter of habit.)

**Comment by PawelStadnicki** [comment]
>  You should be able to work around this by sending each of these separately to the F# kernel.

I've tried many variations, sending them separately, directly via F# kernel or by SubmitCode (code,"fsharp") with the same result

> (Unrelated, the `.Wait()` call makes me a little nervous. 

thanks, yes, there will my proper async handler, but first I wanted to  test the results immediately

**Comment by PawelStadnicki** [comment]
Closing as it seems to work now
