### ISSUE TITLE
Load $PROFILE from PowerShell kernel

### ISSUE THREAD

**Issue by cgranade** [dotnet/interactive#139]
**Is your feature request related to a problem? Please describe.**
It appears that the runspace hosted by the PowerShell kernel does not expose a `$PROFILE` automatic variable, and that no profile scripts are run on startup.

**Describe the solution you'd like**
It would be really handy to be able to load common modules and functions from a PowerShell profile when starting a PowerShell Interactive session, perhaps by using the same `$PROFILE` logic as `pwsh` itself.

**Describe alternatives you've considered**
- Use a `$PROFILE` path specific to .NET Interactive.
- Use the same `$PROFILE` automatic variable, but also set a new automatic variable (e.g.: `[boolean] $IsJupyter`) to allow profiles to tailor their behavior based on the runspace host.
- Expose the same `$PROFILE` automatic variable but with a new property for a Jupyter-specific path that is checked first before defaulting to proceeding to `CurrentUserCurrentHost`.

Thanks for an awesome new way to use PowerShell! 💕

**Comment by Jaykul** [comment]
On the one hand, the jupyter session isn't interactive in the same way as a terminal (there's no prompt!) and the goals of notebooks require them to portable in ways that normal interactive use is not. It would be painful to create a notebook and have it look different for others because they don't have the formatting rules I have in my profile...

On the other hand, I use my profile to customize my interactive PowerShell sessions significantly, not just adding information into my prompt, but also modifying my PSModulePath, fixing up type formats, etc. It's a little painful to me for all of that to be missing. 

Buttom line, I'm torn on this. I don't think I want to run the normal default profile, but I do think maybe we need to support a host-specific `dotnetinteractive_profile.ps1` ... but I will concede that the promise of profile.ps1 is "AllHosts" and it's weird that it doesn't run here...
