### ISSUE TITLE
Cell runs forever when using interactive.csharp.getVariable in conjunction with console.log in a javascript cell

### ISSUE THREAD

**Issue by Treit** [dotnet/interactive#1452]
### Describe the bug
Creating the following .dib file and executing the cells (usually) causes the second cell to run indefinitely:

    #!csharp

    int i = 1234;

    #!javascript

    let x = 0
    interactive.csharp.getVariable('i').then(v => console.log(v))
    console.log(x)

## .NET Interactive Version
Neither `#!about` or `dotnet interactive --version` seemed to work for me, but the vscode extension says it's the following version: v1.0.2309030

- OS
    - [x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/8271812/123719240-e1514c80-d835-11eb-90da-a6c189b0840b.png)

**Comment by colombod** [comment]
You need to await or the promise can complete after the submission is done

**Comment by jonsequitur** [comment]
That doesn't explain why the cell would run forever.

**Comment by RandomFractals** [comment]
per my read of it, output should be 0.

**Comment by jonsequitur** [comment]
> maybe more after that promise is fulfilled.

The example code has a race condition. If the cell execution completes before the promise is fulfilled, you'll only get the `0` output, which is by design. This is what I see most of the time. Occasionally though (and presumably more often on some hardware) it does either print both outputs and complete **_or_** run forever. 

If I await the promise, I see both outputs 100% of the time, and can't reproduce the endlessly-running cell. This suggests to me that the race condition is the reason the cell execution doesn't complete, which would be a bug in our JavaScript evaluation code in the VS Code extension. @RandomFractals  or @Treit, do you see the same when running this:


```js
let x = 0
console.log(await interactive.csharp.getVariable('i'))
console.log(x)
```



@brettfo?

**Comment by Treit** [comment]
> @RandomFractals or @Treit, do you see the same when running this:
> 
> ```js
> let x = 0
> console.log(await interactive.csharp.getVariable('i'))
> console.log(x)
> ```

No, I do not see the cell get stuck running when using the above code.

**Comment by jonsequitur** [comment]
Closing this as `interactive.csharp.getVariable` has been removed as `#!share` is now supported in JavaScript kernels.
