### ISSUE TITLE
Is Visual Basic VB supported for notebooks?

### ISSUE THREAD

**Issue by kevmoens** [dotnet/interactive#1499]
### Question
I opened visual studio code and installed .NET 5 and the .NET Interactive Notebooks in visual studio code.  I saw that c# needs #!csharp and it worked with C#.  #!js worked with node js.  #!fsharp works with f#.  Is there support for VB?  I tried #!vb #!basic #!visualbasic  all with no luck.

**Comment by jonsequitur** [comment]
Visual Basic is not supported because there's no interactive dialect for it.

**Comment by popasUC** [comment]
Any idea when will there be an "interactive dialect" for Visual Basic .Net?

Why is Microsoft leaving Visual Basic so much behind?
The lack of this "interactive dialect" for Visual Basic was an issue two years ago and, it seems, nothing has been done since.
Are there technical roadblocks for Microsoft to create this?
Not sure why this was closed so hastily: https://github.com/dotnet/roslyn/issues/51062

Historically, BASIC and Visual Basic provided an "interactive" experience for programmers, before C# was even born. And VB.Net is still highly popular to this day.

Big fan of Notebooks! … But why were F# and PowerShell supported before Visual Basic .Net? The later is more popular than the former two together.
It seems so misleading to name it ".Net Interactive" and support PowerShell but not Visual Basic .Net …
