### ISSUE TITLE
XPlot.Plotly and ConfigurationBuilder cannot coexst

### ISSUE THREAD

**Issue by onionhammer** [dotnet/interactive#1505]
### Describe the bug
Cannot load configurationbuilder in a notebook with XPlot.Plotly, works fine until XPlot.Plotly is loaded

© 2020 Microsoft Corporation

Version: 1.0.235701+3881a96164de75fca84f5f11027f3606b7878044

Build date: 2021-07-08T03:41:26.0000000Z

https://github.com/dotnet/interactive

- OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Other (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/969938/126878515-faf35745-6530-445e-b6f6-1d02b94bb4c4.png)

**Comment by colombod** [comment]
The issue is also present when the `using` directive is in its own cell:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/375556/189966222-bbb86fe7-81df-43e7-8158-e1bcb8ef0129.png">

the code works if the notebook has one cell for each `#r` instructions:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/375556/189966113-6305a479-afc8-4472-af50-49583db0eee4.png">
