### ISSUE TITLE
Consistency between PowerShell versions

### ISSUE THREAD

**Issue by wsmelton** [dotnet/interactive#175]
**Is your feature request related to a problem? Please describe.**
I'm getting different versions of PowerShell based on what method I use to interact or call commands:

Notebook - PowerShell 7
Console - PowerShell 7
Terminal - Windows PowerShell 5.1

**Describe the solution you'd like**
I would like a consistent version of PowerShell be used across all three methods. My preference would be to match up to what a notebook would be using.

**Describe alternatives you've considered**
A configuration option to control this would be nice.

Reference:

![image](https://user-images.githubusercontent.com/11204251/75070636-44500800-54b9-11ea-9540-7fb208108374.png)

**Comment by TylerLeonhardt** [comment]
@wsmelton can you clarify what Console and Terminal are in this context?

**Comment by wsmelton** [comment]
Added screenshot @TylerLeonhardt for reference.

**Comment by TylerLeonhardt** [comment]
This is something provided by Jupyter Lab so I don't think we can do anything here. [Looking at the docs] (https://jupyterlab.readthedocs.io/en/stable/user/terminal.html#terminals) it says:

"JupyterLab terminals provide full support for system shells (bash, tsch, etc.) on Mac/Linux and PowerShell on Windows"

My guess is that they mean Windows PowerShell here.

**Comment by wsmelton** [comment]
But why would I get PS 7 for one and not the other?

I could not find anywhere I could change what the terminal was using.

**Comment by TylerLeonhardt** [comment]
@wsmelton here's the difference.

Notebook and Console are both using the PowerShell kernel. If you look at the Console experience, it still _looks_ like a Notebook. It has essentially taken the Notebook experience and turned it into this console-like experience.

Terminal on the other hand is actually just a terminal directly from your machine and has nothing to do with Notebooks at all. It's kinda like VS Code's Integrated Terminal experience (that will give you a PowerShell or cmd or bash or whatever terminal inside of VS Code).

There's nothing this repo can do about what shell is used in the Terminal in Jupyter Lab because no jupyter kernel is involved in that experience. I think you may want to chime in on this issue:

https://github.com/jupyterlab/jupyterlab/issues/4034

which talks about allowing you to configure the shell used in the Terminal experience in Jupyter Lab.

**Comment by daxian-dbw** [comment]
Close as it's an external issue.
