### ISSUE TITLE
Resetting C# kernel to fresh state?

### ISSUE THREAD

**Issue by mikoskinen** [dotnet/interactive#2304]
The C# kernel has quite a high memory footprint and it takes a while to construct a new one so we're thinking of pooling C# kernels. 

Is there a safe way to reset the C# kernel so that we could reuse a single kernel safely? The idea is to avoid any surprises in SubmitCode so it would be great if we could clear the declared variables etc. between the commands. I suppose clearing the kernel.ScriptState would be a start?

**Comment by jonsequitur** [comment]
There's definitely work to be done improving performance in this area. But since most of the interesting state in the `CSharpKernel` is in the `ScriptState` and associated resources, and most of the user-perceptible startup time is spent in initializing the script engine, it's not clear that this would solve the issue. Clearing or resetting it would be functionally equivalent to just creating a whole new instance. 

I'd be curious to know more about your usage pattern and whether you'd like to share any profiling findings.
