### ISSUE TITLE
Commenting-out code in cells does not work after last update

### ISSUE THREAD

**Issue by kkoziarski** [dotnet/interactive#2559]
### Commenting-out code does not work after last update

Cannot comment-out code using `CTRL+/` nor `CTRL + K, CTRL + C.` There is no possibility to comment-out code other than typing `//` manually. 

Also auto closing brackets stopped working.

Tested for both C# and JavaScript cells. It worked perfectly before update to the last version.

**Version**
> Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4
> Library version: 1.0.0-beta.22606.2+9bf026dabac44a6256a65168fa93dcb7e2edcca4
> Build date: 2022-12-08T07:51:24.4686906Z

- OS
    -  Windows 10
    - Windows 11

 - Frontend
    - Jupyter Notebook
    - Polyglot Notebook
    - Visual Studio Code

**Comment by Alkasai** [comment]
Same issue here.
And it works everywhere else in VS Code.

**Comment by Jordan466** [comment]
This version also breaks code color, and auto closing brackets.
![image](https://user-images.githubusercontent.com/24884680/210489218-87dcbf15-e57f-45ac-bbc9-8dd880237b50.png)
(I presume all of these issues are probably related, so I thought I'd post it here)

**Comment by GF-Huang** [comment]
This issue seems merged at 2023-01-07, but the latest `Polyglot Notebooks` still has this issue.

Why in VSCode it's `v1.0.3`? But in [marketplace.visualstudio.com](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode) it's `1.0.4`? I had tried uninstall and reinstall from `marketplace` website. It still show me `v1.0.3`.

![image](https://user-images.githubusercontent.com/4510984/214485930-d7d7abd2-8932-4916-9cf3-37545423de16.png)

![image](https://user-images.githubusercontent.com/4510984/214486173-5f331ff1-0624-4003-b886-30e1ccdadf60.png)

**Comment by kkoziarski** [comment]
Same for me - still waiting for update...

**Comment by jonsequitur** [comment]
This is fixed in VS Code Insiders.
