### ISSUE TITLE
Any requirements regarding NuGet packages that can be installed?

### ISSUE THREAD

**Issue by Expecho** [dotnet/interactive#257]
#### Describe the bug
I was trying to create a notebook to experiment with using them for coding exercises and educational purposes but I run into an issue straight away.

Given the following line

    #r "nuget:System.Threading.Tasks.Dataflow"

the output hangs indefinitely with the text 

> Installing package System.Threading.Tasks.Dataflow...........

I tried restarting the kernel etc. but it did not solve the issue hence I suspect it is something inside the [package](https://www.nuget.org/packages/System.Threading.Tasks.Dataflow/). Are there any specific requirements to deal with?

#### Did this error occur while using `dotnet interactive`?
- [x] .NET Jupyter Notebook 

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Safari
 - Frontend
    - [x] Jupyter notebook
    - [ ] Jupyter lab
    - [ ] nteract

**Comment by jonsequitur** [comment]
Could you run `#!about` or `dotnet-interactive --version` and post the version you're using?

**Comment by Expecho** [comment]
> Could you run `#!about` or `dotnet-interactive --version` and post the version you're using?

I am using online Binder.

Version: 1.0.115407+d247e88f3f756abad4bd16b47cf8cde187aafabc
Build date: 2020-03-05T04:56:06.0000000Z

**Comment by Expecho** [comment]
I have tried nteract as well, same result.

**Comment by KevinRansom** [comment]
@Expecho ,  Hi, I have taken a look at this.  System.Threading.Tasks.Dataflow is a framework assembly and is preloaded by the interactive session.

There is however, a UI bug here, when we do a package load, and it results in no dll loaded, because for example it is already loaded, we don't update the UI.

Here you can see the package load starts, displays a message, end then evaluates the rest of the script.

![image](https://user-images.githubusercontent.com/5175830/77220838-66ad6380-6b01-11ea-978c-a164bef40942.png)

I hope this clears it up.

Kevin

**Comment by Expecho** [comment]
Hmm ok, I assumed it was more than a display bug due to the fact that the following code does not run:

    var x = new System.Threading.Tasks.Dataflow.ActionBlock<int>((i) => {});

When I put that in it fails:

![image](https://user-images.githubusercontent.com/11960665/77233686-68cafd00-6ba9-11ea-96be-ec35376515be.png)

and I triple checked the code and it compiles everywhere else.
