### ISSUE TITLE
using statement declaration without braces does not work (IDisposable)

### ISSUE THREAD

**Issue by kkoziarski** [dotnet/interactive#2620]
### Description
`using` statement declaration without braces does not work (IDisposable). You cannot use `using` without braces.

Example:
```csharp
using var x = new ALogger();

Console.WriteLine("not working...");

public class ALogger : IDisposable
{
    public void Dispose()
    {
        Console.WriteLine("Finishing...");
    }
}
```

### Version

Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4

Library version: 1.0.0-beta.22606.2+9bf026dabac44a6256a65168fa93dcb7e2edcca4

Build date: 2022-12-08T07:51:24.4686906Z

- OS
    - [X] Windows 11
    - [X] Windows 10

 - Frontend
    - [X] Visual Studio Code 

### Screenshots
Polyglot Notebook:
![image](https://user-images.githubusercontent.com/6848262/212561831-f2425287-90a8-4e7f-95e3-e2f73c665f3b.png)

It works in Visual Studio 2022:
![image](https://user-images.githubusercontent.com/6848262/212561854-2e477923-8769-43c9-9c13-e3ac55e7007a.png)

**Comment by brettfo** [comment]
The reason this doesn't work is because the C# language used in notebook cells is the script dialect which differs slightly from the "normal" project dialect.

Going a little deeper, it's ultimately because in the script dialect, `x` is technically a field on a class, so to get the behavior you're looking for (i.e., scoped) you need the one with parentheses and brackets like in your second example.
