### ISSUE TITLE
[BUG] [SECURITY] Can close host app from script

### ISSUE THREAD

**Issue by ParadiseFallen** [dotnet/interactive#2715]
### Describe the bug
```cs
System.Environment.Exit(0);
```
^^^ will close host app.

Basically need a way to prevent exiting from host app

- OS
    - [x] Windows 11
    - [ ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [ ] Visual Studio Code 
    - [ ] Visual Studio Code Insiders
    - [ ] Visual Studio
    - [x ] Other (please specify)

```cs
var kernel = new CSharpKernel()
                    .UseNugetDirective()
                    .UseKernelHelpers()
                    .UseWho();

while (true)
{
    if (ReadLine() is not { } request) // enter `System.Environment.Exit(0);`
        continue;
    var toSubmit = new SubmitCode(request);
    var response = await kernel.SendAsync(toSubmit);
    response.KernelEvents.Subscribe(
        e =>
        {
            switch (e)
            {
                case CommandFailed failed:
                    WriteLineError(failed.Message);
                    break;
                case DisplayEvent display:
                    WriteLine(display.FormattedValues.First().Value);
                    break;
            }
        });
}


static string? ReadLine()
{
    Console.Write("\nInput: ");
    return Console.ReadLine();
}

static void WriteLine(string input)
{
    Console.ForegroundColor = ConsoleColor.DarkGreen;
    Console.WriteLine($"\nOutput: {input}");
    Console.ForegroundColor = ConsoleColor.Gray;
}

static void WriteLineError(string input)
{
    Console.ForegroundColor = ConsoleColor.Red;
    Console.WriteLine($"\nError: {input}");
    Console.ForegroundColor = ConsoleColor.Gray;
}

```

**Comment by brettfo** [comment]
Given that our host app is net7.0 this is expected behavior.

**Comment by ParadiseFallen** [comment]
@brettfo then is there a way to isolate modules?

**Comment by brettfo** [comment]
> ...need a way to prevent exiting...

The design of the CLR is that calling `Exit(int)` will exit the process and it can't be intercepted.  [Link](https://github.com/dotnet/runtime/blob/cbc8695ae0c8c2c2d1ac1fc4546d81e0967ef716/src/coreclr/System.Private.CoreLib/src/System/Environment.CoreCLR.cs#L20-L26)

You could try using the Roslyn APIs to analyze the submitted code before executing it and look for a call to the `Exit()` function, but that's going to be a never ending trail because the end user could always use reflection to find the function and call it, or the user might have linked to another library that itself calls `Exit()` that you can't intercept.
