### ISSUE TITLE
VS Code Server has no PowerShell support beyond basic kernel execution

### ISSUE THREAD

**Issue by K8-and-a-half-1000** [dotnet/interactive#2801]
### Describe the bug

I've updated this bug after initial triage.

#### Reproduction steps
Run `code.exe tunnel`
Install Polyglot Notebooks and recommended packages.
If I run the following command from the command pallet:
`Polyglot Notebook: Create default notebook`

Syntax highlighting is broken, autocompletion works, but IntelliSense error highlighting is broken.

Thanks for your time and consideration.

### Please complete the following:

- OS
    - [x] Windows 11
 - Frontend
    - [x] Visual Studio Code Server

**Comment by jonsequitur** [comment]
The issues you're seeing aren't related to the file extension, and PowerShell is working generally. There are two different, unrelated issues I think you might be hitting. 

> As a result syntax highlighting is broken...

Lack of code coloring is a known issue (#2683) and it's unrelated to the other issue you're seeing.

> ...autocompletion is broken, and extensions for PowerShell are not applied.

When code won't run or completions aren't working, it's usually because there's a pending VS Code update, which often then triggers a Polyglot Notebooks extension update. Please click the gear icon in the lower left of VS Code and select `Check for updates`. Then also check (after an update was applied, if there is one) in the extensions item in the sidebar to see if there's a `Reload required` button under the Polyglot Notebooks extension.

> The language should be PowerShell and not Code.

The separation of the kernel chooser from the "Language Mode" chooser (Code vs Markdown) is a recent design change. It's possible in Polyglot Notebooks to add multiple subkernels for the same language (for example, multiple SQL connections to different databases). Choosing just the language is insufficient, so we added the more detailed chooser which shows both the kernel name and the language used by that kernel.

**Comment by K8-and-a-half-1000** [comment]
I've started an up-to-date Windows 11 Pro VM, installed VS Code and the Polyglot Notebook extension and created a new notebook.

As you said, the colorization and IntelliSense work just fine.

I assume this is update related on my VS code Server instance.
I've been running it since beta preview, but can't recall seeing any updates.

**Comment by jonsequitur** [comment]
VS Code updates once a month, typically in the first week of the month. The updates are often very subtle, unless they break something. I'm not sure if the update cycle works differently for VS Code Server or if there's something about your server configuration that's preventing updates.

**Comment by K8-and-a-half-1000** [comment]
You don't see the updates on VS Code Server so you can't update it remotely. 
VS Code and VS Code Server are the same executable; the latter is just `code.exe tunnel` with some additional setup.

I've updated VS Code by running it without the tunnel command, and checking for updates.
That fixed the IntelliSense and colorization, but only when I run `code.exe`.

When I run `code tunnel` only the IntelliSense suggestions work.
Colorization doesn't work, and error-highlighting doesn't work.

**Comment by K8-and-a-half-1000** [comment]
I've resolved this issue by uninstalling `.NET interactive` and switching to the baseline Python implementation instead.
That one works out of the box.

![image](https://user-images.githubusercontent.com/75888141/224044347-0e7c165a-846b-473c-b1b8-ab297579d1fa.png)
