### ISSUE TITLE
No apparent way to unload a Nuget package after #r, to support reloading an earlier package

### ISSUE THREAD

**Issue by dullroar** [dotnet/interactive#342]
**Is your feature request related to a problem? Please describe.**

Before I came across issue #50 I wanted to try using Google charts, so I added the following:

```cs
#r "nuget:XPlot.GoogleCharts,3.0.1"
```
Then, when I try the following:

```cs
var geoPlot = XPlot.GoogleCharts.Chart.Geo(
    byDensity.Select(i => i.Item3),
    byDensity.Select(i => i.Item1)
);
display(geoPlot);
```
...I get the following error:

```
(1,15): error CS1705: Assembly 'XPlot.GoogleCharts' with identity 'XPlot.GoogleCharts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'FSharp.Core, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'FSharp.Core' with identity 'FSharp.Core, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
OK, so let's go change that `#r` to try an earlier version of the package with dependencies on an earlier version of `FSharp.Core`:

```cs
#r "nuget:XPlot.GoogleCharts,3.0.0"
```
But that yields:

```
XPlot.GoogleCharts version 3.0.0 cannot be added because version 3.0.1 was added previously.
```
Spent hours now looking at the source code here, reading about CSX scripting and the commands available there, to no avail. It looks like (on Linux Mint) the library is installed at `~/.nuget/packages/xplot.googlecharts`, but I don't want to just delete that directory, since I am worried that isn't the right way to do it.

**Describe the solution you'd like**

Some way, either through the notebook menu or with something like an `#unload` or magic command to remove a nuget package to then allow replacing it.

**Describe alternatives you've considered**

* Deleting the above `.nuget/packages` subdirectory, but I fear breaking something.

* Looked at the raw `.ipynb` file for my notebook, but didn't see anything leap out at me there.

**Comment by jonsequitur** [comment]
This is by design in .NET Interactive. The solution, for now, is to restart the kernel and install the version you need.

Picture this sequence of submissions:

```csharp
#r "nuget:DinosaursLib,1.0.0"
var brontosaurus = new Brontosaurus();
var dinosaurs = new List<Dinosaur>
{
  brontosaurus
};
```

...and then, assuming we allowed referencing a second version (which, it's worth pointing out, C# scripting *does* allow for `.dll` references):

```csharp
#r "nuget:DinosaursLib,2.0.0" // new version of DinosaursLib, where Brontosaurus is obsolete
var dinosaurs.Add(new Apatosaurus());
```

The second submission gives a compile error because we've loaded two versions of `DinosaursLib` and we have two different `Dinosaur` types, but our `dinosaurs` list references `Dinosoaur` from version `1.0.0`. 

This kind of error is pretty confusing and hard to reason about, especially when it crops up (as it usually will) in transient references. It's also hard to recover from because you already have a bunch of compiled code from earlier in the session referencing the older version. It still can't really be solved without restarting the kernel.

We did consider just loading these into separate `AssemblyLoadContext` instances. While it might address some special cases, it's still very hard to reason about.

Hope that makes sense. Thoughts?

**Comment by dullroar** [comment]
> This is by design in .NET Interactive. The solution, for now, is to restart the kernel and install the version you need.

Doh! So simple! I thought it must be a permanent part of the notebook.

> Hope that makes sense. Thoughts?

That does make sense. Thanks for the quick turnaround. And I learned a lot just playing around on a Saturday morning along the way.

Closing the ticket.
