### ISSUE TITLE
How to render HTML contained in a C# string

### ISSUE THREAD

**Issue by rzippo** [dotnet/interactive#3499]
I have C# code that creates a string with HTML code, like this one

```html
<!DOCTYPE html>
<html>
<head>
    <title>MathJax Test</title>
    <script src='https://polyfill.io/v3/polyfill.min.js?features=es6'></script>
    <script id='MathJax-script' async src='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'></script>
</head>
<body>

    <div id='output-0'></div>
    <script>
        document.getElementById('output-0').innerHTML = '\\( \\alpha + \\beta \\)';
        MathJax.typeset();
    </script>
</body>
</html>
````

If this HTML is put in its own HTML cell, it renders correctly like this
![immagine](https://github.com/dotnet/interactive/assets/16462616/4bbfa6b2-0578-4a43-9645-55fd28a07f4b)

But if I try to render the C# string containing the HTML, I only get the text.
![immagine](https://github.com/dotnet/interactive/assets/16462616/3b013e3c-0a37-4e82-9ff3-31eb50c4c832)

How do I get the string to be interpreted and rendered as HTML?

**Comment by jonsequitur** [comment]
This is happening because the `Display` method will HTML encode the string. 

When you know that the string is already valid HTML and you don't want to encode it, you can use `DisplayAs("text/html")`:

![image](https://github.com/dotnet/interactive/assets/547415/c721bfa9-4554-4173-9512-0542b171bd9a)

**Comment by rzippo** [comment]
It works, thanks!
