### ISSUE TITLE
change file extension for VS Code notebooks

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#433]
The current file extension, `.dotnet-interactive`, is a placeholder. We should come up with something more concise.

**Comment by LadyNaggaga** [comment]
Here are some suggestions 

- .dib - dotnet interactive book

- .dibs - dotnet interactive book scripts 

- .dsx - dotnet scripts

- mls - multi
-  dni - dotnet interactive 
-  .inet - interact

**Comment by colombod** [comment]
- .dsx
- .dni
- .mls

**Comment by LadyNaggaga** [comment]
- dibs 
- dsx
- dib 
"Hey can you share that .dibs file ?"
" Do you have that dibs file"?

**Comment by BillWagner** [comment]
I think my favorite is 
- .dni

What about:
- .icsn
- .innb (interactive .net notebook, pronounced "inn-bee".

It will show my age, but a "dib" once referred to a "device independent bitmap".

**Comment by csharpfritz** [comment]
I’ve got dibs on this one.

**Comment by glennc** [comment]
I liked the idea of having NB for notebook in it.
 - dnnb : has no real results if I google for it.

Most of the suggestions so far have common files that exist with that extensions. That's not necessarily a show stopper. But it'd be nice if there wasn't a conflict.

**Comment by glennc** [comment]
No real results in terms of an existing file extension that is :)

**Comment by LadyNaggaga** [comment]
@glennc  and @BillWagner  I like both your suggestions. .NET Interactive isn't purely for notebooks so, we were trying to leave out of the name. But, I really like both your suggestions 
-  dnnb  : dotnet notebooks 
- .innb (interactive .net notebook, pronounced "inn-bee".
cc @jonsequitur  thoughts

**Comment by jonsequitur** [comment]
I think the "nb" suffix helps make the association to notebooks so even though these files are also usable as automation scripts, that might be less important.

**Comment by shanselman** [comment]
oh my it's gotta be .dnb, dni, dib, any of those.

**Comment by jongalloway** [comment]
Yep, was thinking .dnb too. Three letters is best and dnb is fun anyways because

<img src="https://68.media.tumblr.com/a8d2d0d6815e08f5031e675f5d497e5d/tumblr_inline_nbbv8cVHr31sm0vgm.gif"/>

**Comment by LadyNaggaga** [comment]
Thanks @jongalloway  and @shanselman I kind of like dnb  because it could be dotnet books or dotnet notebooks. 
Low-key  I am still rooting for . dib

**Comment by bradygaster** [comment]
with all due respect I don't like the `.dni` option. I can't not think of "DNI" - 'do not resuscitate'. my favorite was `dib` but now I think I like `dnb` better. I mean, I was a d'n'b dj for a moment. 

but not dni.

**Comment by LadyNaggaga** [comment]
@bradygaster good point about .dni.  I also immediately think about D&I as well. 

Looking at the options so far these three seem to resonate 
-  **.dib**- dotnet interactive book 
Pros: Catchy and simple.  Identifies it as .NET being interactive and can also be used in notebooks. 
Cons: used to be device independent bitmap. Seems like it hasn't been used for a while.
- **.dnb** - dotnet notebooks
Pros: Simplicity. It immediately resonates with a ecosystem the exist without mimicking it. 
Cons: DNB file is a Microsoft Windows DNS Binary DNS Database.
- **.dnnb** - **d**ot**n**et **n**ote**b**ooks
Pros: Not in use. Simple and resonates with an existing ecosystem.

**Comment by gcrev93** [comment]
I like **.dib** and **.dnb**

But looking at the pros and cons @LadyNaggaga has listed **.dib** is the best choice since device independent bitmap hasn't been used in awhile

**Comment by captainsafia** [comment]
I'd vote for `dib` first and `dnb` second.

I'm a bit of the fan of the "interactive book" because it does a better job of explaining what the document is for than notebook. The term "notebook", popularized by Jupyter (and MATLAB before that) is a child of the academic origins of these technologies -- but is super easy to conflate with others thing, like a OneNote notebook, for newbies to the ecosystem. It also obfuscates the best parts of these technologies: the interactivity portion.

I like that `dib` highlights _how_ the document works (it's interactive!) instead of just what it is (it's a a notebook!).

Also, TBH, from my experience whether or not "nb" exists in the file extension won't really affect whether people colloquially refer to it as a notebook or not. That depends more on how it functions (does it have code cells, does it have outputs, does it have the concept of a "run cell") than what's in the file extension. So you can get away with not having `nb` in the extension but still using `notebook` in the marketing to indicate what it's all about it.

Anyhoooo, I'll stop rambling now but you can tell which one I am passionate about. :P

**Comment by LadyNaggaga** [comment]
💯  @captainsafia

**Comment by bamurtaugh** [comment]
My top two choices are `.dib` and `.dnb`, in that order. 

I agree that it's nice to keep "interactive" as part of the extension name so that this isn't thought of as *just* a notebook solution, and so that the transition from `.dotnet-interactive` -> `new-extension-name` is smooth. But `.dnb` is a really close and nice second choice.

I also can't help but think of all of the demo fun you could have when saying it's time to open your `dib` file 😄

**Comment by briacht** [comment]
I agree -- .dib or .dnb sounds best to me 👍

**Comment by mairaw** [comment]
I really like **dib**. It's catchy, rolls off your tongue, and represents the product well.

I dislike dni. I think the acronym could conflict with other things as well (dotnet interop, dotnet installer, etc.) even though I know we're choosing a file extension not am acronym per se.

**Comment by jonsequitur** [comment]
I also like `.dib` but wonder if the fact that Windows has a default icon for it would confuse people. Maybe not a big deal once people change their file association to VS Code?

![image](https://user-images.githubusercontent.com/547415/82364234-dafe6900-99c3-11ea-87a0-863612e1d71c.png)

**Comment by jonsequitur** [comment]
![image](https://user-images.githubusercontent.com/547415/82371714-806b0a00-99cf-11ea-8abf-548ecbd927cc.png)

**Comment by amarie401** [comment]
My vote is for .dib or .dnb as well! Those two sound the best to me overall :)

**Comment by amarie401** [comment]
My vote is for .dib or .dnb as well! Those two sound the best to me overall  - though, I'm slightly leaning towards .dib more ;)

**Comment by jonsequitur** [comment]
`.dib` wins.

The latest version of the extension supports this.
