### ISSUE TITLE
VS Code .NET Interactive doesn't honor the custom settings for which dotnet-interactive to use

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#461]
The output reflects the version that the extension is built to target but if I want to use a local dev version, this is misleading:

![image](https://user-images.githubusercontent.com/547415/82604757-9c0a1800-9b69-11ea-8dcc-b2c5031fe478.png)

![image](https://user-images.githubusercontent.com/547415/82606103-623a1100-9b6b-11ea-9852-5942ec199578.png)

**Comment by brettfo** [comment]
The version reported is the local tool version that the extension acquired; it's gleaned from running `{dotnet_path} tool run dotnet-interactive --version`.  While I see your issue, I'm not sure we can create a good experience for what you're asking, because `kernelTransportArgs` can be set to launch _any_ application with _any_ arguments; it doesn't even have to be `dotnet-interactive` and it doesn't have to support a `--version` flag.

From within a notebook you can always execute the `#!about` command to get the version you're executing against, so maybe the issue is that the message placed in the output window shouldn't say `Using version ...`, but instead `Acquired version ...` or similar.

**Comment by jonsequitur** [comment]
I think the message is ambiguous, so that change would be helpful. But the real problem is that this clearly didn't launch the version I had installed globally, which I was trying to debug. How do I accomplish that?
