### ISSUE TITLE
[Question] Is .NET interactive interpret or compile the code?

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/interactive#695]
If it is interpreted, will the performance be slower than the compiled. 

Is there a document that briefly describes the principle without reading the source code.

**Comment by dsyme** [comment]
It is compiled (runtime JIT compiled)

**Comment by GF-Huang** [comment]
Does it compile each user input cell while each user press run cell?

**Comment by dsyme** [comment]
> Does it compile each user input cell while each user press Run Cell?


Yes

**Comment by GF-Huang** [comment]
So how does the cells share runtime environment(variables, classes, etc..)?

**Comment by jonsequitur** [comment]
> So how does the cells share runtime environment(variables, classes, etc..)?

The implementations are language-specific so there are subtle differences. Broadly speaking, each time you submit a cell it compiles a new assembly referencing the previous one. Top-level code (including variables and classes) is shadowed if you redeclare something with a previously-used name. Consider these two submissions:

```csharp
int x = 123;
public int GetX() => x;
```
```csharp
string x = "hello";
```
In effect, the second submission declares a second variable of a different type. It's no longer possible to reference the original `int x` in a later submission, but because the `GetX` method was compiled against that original `int x` declaration, the later `string x` declaration is irrelevant to it, and `GetX` will always return `123`.

**Comment by GF-Huang** [comment]
Understood, thank you.
