### ISSUE TITLE
VS Code crash when running specific PowerShell code

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#730]
Running the following code crashes Visual Studio Code

```powershell
$PSVersionTable

Get-Module -ListAvailable
```

![image](https://user-images.githubusercontent.com/9363027/91368089-019b1f80-e7bd-11ea-8def-9832f66fd3ad.png)

![image](https://user-images.githubusercontent.com/9363027/91368133-22637500-e7bd-11ea-99ea-6fb62bf187d3.png)

**Comment by jhoneill** [comment]
It may be not be the same cause but get command causes an error which dumps a stack-trace in the Jupyter the error begins with 
Microsoft.DotNet.Interactive.PowerShell.Host.Progress.ProgressPane.Hide
Is it trying to do something with a progress pane which is never created ?

**Comment by Szeraax** [comment]
I'll note that it must not be the number of objects in the prior to rendering, since this command hangs:

```
ls | select -first 3 
Get-Module -ListAvailable
```

But this one works:
```
ls | select -first 3 
Get-Module -ListAvailable | ft
```

It would seem that it is based on the raw number of lines returned, not PSObjects returned. 

based on that, I did some benchmarks to see how the number of output lines affected how long it took till the command was marked as completed. In ALL cases, the final line of text was returned immediately. It did have the "show more (open in new)" link cutting out all the middle stuff from about row 25..(n-5). 

At longest, I did 1000 rows output and it took ~47s to "complete", despite row 1000 showing up instantly in my window. Here's it charted with a LOG scale: 

![image](https://user-images.githubusercontent.com/6242511/145171486-76ebd75e-1487-4601-9238-6bc2b7d43200.png)

**Comment by jonsequitur** [comment]
It looks like the issue isn't with the kernel but in the way command completion is signaled to the VS Code extension. In the following example, I could run another command while the PowerShell command appeared to be still hanging.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/547415/145287512-97d067c2-4068-4472-988a-7bff4e34e044.png">
