### ISSUE TITLE
Out-Display not working as expected in VS Code. 

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#769]
### Describe the bug
I've been experimenting outputting SVG, which worked in Jupyter with an older version of .Net Interactive, but not in VS Code, eventually I simplified this down to _any_ HTML markup not working, with this simple example
```
"<body><b>Test<b><body>" | out-display -mimetype "text/html"
```
On  1.0.115407 / Jupyter  outputs **Test**    -this is preserved if I save the file and re-open in vscode.
On 1.0.145905 / VS Code outputs `<body><b>Test<b><body>`

I can't tell if there is an intentional change in behavior (does out-display need to be called differently), or if Out-display or something downstream from it is failing. 

### Please complete the following:

**Which version of .NET Interactive are you using?**   1.0.115407 (works) and 1.0.145905 (fails)

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [X] Edge  (86.0.622.10)
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [X] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code  (1.49.0-insider)
    - [ ] Other (please specify)

### Screenshots
![image](https://user-images.githubusercontent.com/16209593/92727578-3f747800-f367-11ea-9be8-772cac458822.png)
Above, vs-code failing, below Jupyter working
![image](https://user-images.githubusercontent.com/16209593/92727635-59ae5600-f367-11ea-82c2-3cff294a7085.png)

**Comment by jonsequitur** [comment]
This was somewhat by design, as a result of a recent formatter overhaul, but it's worth discussing this scenario again.

@dsyme We changed this behavior to support formatting all strings in `<div>` elements, rather than rendering them with `text/plain`. Among other things, this allows columnar whitespace layouts to be preserved. 

It also made things a bit more consistent. Two different behaviors were conflated in the `display` API previously, like this:

* `display("<b>hello</b>", "text/html")` -> The input is HTML, please don't encode it.
* `display(someObject, "text/html")` -> Please render a representation of the object into an HTML table.

The first case now encodes the HTML, so the meaning is consistent in both cases: Please transform the input into HTML.

If you want to use a string literal to emit HTML, you can still do this:

![image](https://user-images.githubusercontent.com/547415/92766419-10500d80-f34b-11ea-9846-363a091c09df.png)

In #770 @colombod added some tests to illustrate the original scenario.

So the question is do we think we have the right behaviors and APIs here?

(There's a separate desire to create some more .NETish, less IPythonish alternatives to these APIs, but that's more of a naming discussion and we'll save that for another issue.)

**Comment by jhoneill** [comment]
**THANK YOU**

For PowerShell I had to call html() like this
```
[Microsoft.DotNet.Interactive.Kernel]::HTML($svg) | Out-Display
```
 but it's working nicely :-) 
![image](https://user-images.githubusercontent.com/16209593/92798606-ffcf7f80-f3aa-11ea-8744-75b8245e6bbe.png)

I tweeted this earlier running in Jupyter and now it's in vscode - read a YAML specification of an azure-devops pipeline, draw it as a simple SVG chart. Output to notebook. 
![image](https://user-images.githubusercontent.com/16209593/92798877-3f966700-f3ab-11ea-9674-2aeed020dfd8.png)

**Comment by colombod** [comment]
Wow
