### ISSUE TITLE
[EXTERNAL] Support for directly opening .ipynb files in VS Code

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#772]
It's currently possible to read and write `.ipynb` files by selecting **.NET Interactive: Open notebook** from the command palette, but if you open them using **File: Open** or by opening them from the file explorer, they open in the text editor interface, not the notebook interface.

**Comment by brettfo** [comment]
The Python extension strongly associates with the `.ipynb` extension and according to microsoft/vscode-python#13078 there's no way to directly do this without our special command.  That same issue claims that once notebook support is properly in VS Code stable, then the python extension will be updated to no longer force the association.

**Comment by Spongman** [comment]
i have this issue, and i don't have the Python extension installed.

**Comment by brettfo** [comment]
@Spongman this is expected.  Because the Python extension is so aggressive with its file associations, the `.ipynb` association wasn't added to this extension.  Your best option is to execute the command `.NET Interactive: Open notebook` (internally named `dotnet-interactive.openNotebook`).  From there regular Ctrl+S will work for save.
