### ISSUE TITLE
Console out renders a distinct block per call in VS Code

### ISSUE THREAD

**Issue by jhoneill** [dotnet/interactive#799]
### Describe the bug
I think this may be a generic re-statement of #730 
When PowerShell generates output it sends one or more items to the pipeline, and each one is rendered as a separate block and in the ipynb file each one becomes an object under `outputs` with      
```
"output_type": "execute_result",
"data": {
      "text/plain": 
```
This is different from .net interactive in Jupyter which outputs a single object with an `output type` of `stream`

The objects are then double spaced in the print out and, if there enough objects, VS Code hangs. 
Piping objects through `Out-String` produces a more desirable  behaviour spacing like this:
![image](https://user-images.githubusercontent.com/16209593/94362624-a0fd4c00-00b4-11eb-8e0b-7e3741d76732.png)

When there are **many objects**, using `| Out-string` successfully inserts a large, multi-line text block, where **vs-code hangs** (c.f #730), to repro try `dir c:\windows | out-string` and then re-run the command  removing `| out-String`  On my machine this has 119 files which is sufficient to cause the hang. 

- Version of .NET Interactive 
    - v1.0.146902
- OS
    - [x] Windows 10 -  10.0.19041.0
- Frontend
    - [x] Visual Studio Code 1.150.0

**Comment by jonsequitur** [comment]
Related: https://github.com/microsoft/vscode/issues/107613

**Comment by jonsequitur** [comment]
Related: https://github.com/microsoft/vscode/issues/103661

**Comment by bmitc** [comment]
As detailed in #951 (and also #879 which contains a workaround), when using `printf` and `printfn` in an F# cell, newlines get entered before and after parameterized values. For example, if one runs:

```
printfn "Number = %.2f, String = %s" 2.123 "testing"
```

Then the result looks like this:
![image](https://user-images.githubusercontent.com/65685447/103321548-c7a68800-49ff-11eb-8e77-ae53121f32c3.png)

**Comment by jessiewestlake** [comment]
Does anyone know where on the roadmap fixing this issue is?

Being able to run code and see it's output is the only useful aspect of using Interactive Notebooks. The output is virtually unreadable with this problem. I spent more time setting up the environment to use the .NET Interactive Notebooks than I spent running my first `Get-ChildItem` command and realizing the output is basically unusable.

.NET Interactive Notebooks is an amazing feature and something I could really use to get my team into using VS Code and teaching them PowerShell coding. Please continue working on this. Thank you!

**Comment by jonsequitur** [comment]
This is being tracked here: https://github.com/microsoft/vscode/issues/103661

**Comment by rebornix** [comment]
FYI currently VS Code no longer hangs with above code snippets.
