### ISSUE TITLE
[EXTERNAL] Cannot save dib file if first autogenerated cell is Markdown

### ISSUE THREAD

**Issue by gmlion** [dotnet/interactive#811]
### Describe the bug
If you create a dib file and change the first cell to markdown, you are unable to save with error `Failed to save 'testmd.dib': Cannot read property 'startsWith' of undefined`

### Please complete the following:

**Which version of .NET Interactive are you using?**

1.0.148003+8db7ff4b2bd09c703e7d5dc39d8adb9899d5e5c7

- OS
    - [X] Windows 10

 - Frontend
    - [X] Visual Studio Code

### Screenshots
![immagine](https://user-images.githubusercontent.com/6882159/94778604-df9d4a00-03c5-11eb-8069-652d3a14f439.png)

**Comment by brettfo** [comment]
Thanks for filing the bug.  We've seen this before but didn't know the exact steps that caused it, but now we do.

The issue comes from VS Code itself so I created issue microsoft/vscode#107917 on them to fix it.  This issue will be left open until we've confirmed the fix is in the next VS Code Insiders build.

Until then a workaround is to add a new Markdown cell directly instead of changing the language of an existing cell and copy/paste the contents into it.
