### ISSUE TITLE
VS Code frontend looking for files in wrong directory

### ISSUE THREAD

**Issue by tonytins** [dotnet/interactive#931]
### Describe the bug

Occasionally (if not all the time), the VS Code frontend looks in the extension's directory instead of the one you're in when trying to locate files. This only seems to happen upon first creating the notebook. Closing and re-opening it seems to be the only workaround I've discovered for the issue.

### Please complete the following:

**Which version of .NET Interactive are you using?**
1.0.160204+9a96ad3eee7b38d6db907a97513009e04f967825

- OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [x] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots

![](https://i.imgur.com/Ewp9xDE.png)
![](https://i.imgur.com/s5YyN6M.png)

**Comment by brettfo** [comment]
@jonsequitur @colombod I'm interested in your thoughts here.

The issue arises when we create a new notebook.  At that point in time the notebook doesn't exist on disk and we have no idea where to set the working directory, so it defaults to our extension's global storage path, e.g., `c:\Users\<username>\AppData\Roaming\Code - Insiders\User\globalStorage\ms-dotnettools.dotnet-interactive-vscode`.  I don't think there's anything else we can currently do here because we can't divine their desired location.  We could, however, add an extension variable `defaultNotebookLocation` or similar that we could default to.  My issue with that is one of discoverability and actual utility; I don't think it'll get used.

The next step is when the user saves the notebook for the first time.  Currently we do nothing so the working directory is still the global storage path.  At this point we can easily detect that it's a new file being saved for the first time and issue a `ChangeWorkingDirectory` command to the kernel, and that may be desirable __unless__ the user has already set it on their own, but we have no real way of discovering that.

The final step is if the notebook is closed and reopened __then__ the working directory is set as expected.  This part is fine.

My suggestion is paragraph 2: if we're saving a notebook for the first time, issue a `ChangeWorkingDirectory` command to the kernel.  This will work in most cases, *except* where the first thing a user does with a new notebook is something with the current directory and we come along and modify it out from under them, but I imagine this will be a tiny set of scenarios, certainly smaller than those that create a new notebook, save it somewhere, then do stuff that depends on the working directory.

**Comment by jonsequitur** [comment]
> The issue arises when we create a new notebook. At that point in time the notebook doesn't exist on disk and we have no idea where to set the working directory, so it defaults to our extension's global storage path

I think the ideal experience would be the directory where VS Code was started. For example, if I do this:

```console
> code /some/path
```

and then I create a new document and save it, the file save dialog defaults to `/some/path`. Can we access that path and use it as the working directory for a new blank notebook?

**Comment by colombod** [comment]
does this repro with latest version of the extension?

**Comment by brettfo** [comment]
We now explicitly set the working directory to whatever directory contains the notebook, or if it's a new untitled one, we use the vscode workspace directory.  Only if all of those fail do we use the extension directory, but at that point that's the only thing we can do.
