### ISSUE TITLE
VS Code extension failing on macOS

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#933]
![image](https://user-images.githubusercontent.com/547415/101381880-25660b00-386c-11eb-9691-e7d870adeb50.png)

This repros on macOS Big Sur 11.0.1. It does not repro on Catalina 10.15.7.

**Comment by jonsequitur** [comment]
Related: #875.

**Comment by jonsequitur** [comment]
![image](https://user-images.githubusercontent.com/547415/101521759-19954a00-393b-11eb-834d-c954ebc9af91.png)

**Comment by brettfo** [comment]
@jonsequitur The interesting item from your screenshot is `failed: Unable to create local tool manifest.`  That looks like a directory permissions issue because [here](https://github.com/dotnet/interactive/blob/2f30b1841bb7a6555196b94c4c7d829c1ad362e1/src/dotnet-interactive-vscode/src/vscode/commands.ts#L198) we run `path/to/dotnet new tool-manifest` with a working directory of, e.g., `c:\Users\brett\AppData\Roaming\Code - Insiders\User\globalStorage\ms-dotnettools.dotnet-interactive-vscode` (obviously different in MacOS.)

Can you set a breakpoint at that location to see the value of the `globalStoragePath` variable then check its permissions?  Also check the value of `dotnetPath` and try running that command manually to see if there's an error message that we can act on?

**Comment by brettfo** [comment]
I created PR #937 to report more data when this type of failure happens so we can hopefully figure out more.

**Comment by jonsequitur** [comment]
I realized that on the Mac I hadn't installed .NET 5. 

Is there a way we can detect this and provide a more helpful error?

**Comment by brettfo** [comment]
If you don't have .NET 5 installed we _should_ be able to install a runtime for you, but the error you were seeing was because that somehow failed.  The extra error text I added in #937 should help diagnose this in the future.

@jonsequitur The extension with that extra text has been published, do you feel like uninstalling .NET 5 on your mac and trying the scenario again to see if we can get an actionable error?

**Comment by jonsequitur** [comment]
When was it published? I did uninstall .NET 5 to verify the repro this morning.

**Comment by brettfo** [comment]
Version 1.0.160901 was published 12/9 at 5:24 AM PST.  If you have that version with no .NET 5 installed then the issue appears to not repro currently.

I'm wondering if it's related to the global storage path existing on disk?  Can you try the following:

1. Ensure you have extension >=1.0.160901.
2. No .NET 5 installed.
3. Delete extension's global storage directory.  I don't have a mac to check this, but I think it's the following directory: `~/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.dotnet-interactive-vscode`
4. Re-launch vscode and create a new notebook.
